# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

lang: en
timezone: # e.g., Asia/Manila or America/New_York (Leave blank or fill according to your locale)

# jekyll-seo-tag settings
# ↓ --------------------------

title: The Triage Log # Update your blog title

tagline: A technical writing log by Danny Garcia # Update your subtitle/tagline

description: >- 
  Deep dives into reverse engineering, forensics, reproducible builds, and blockchain tech.

url: "https://xrviv.github.io"
baseurl: "/The-Triage-Log"

github:
  username: xrviv 

twitter:
  username: # Your twitter handle (or leave blank/delete line if you don't use it)

social:
  name: Danny Garcia # This fixes the copyright/footer name
  email: your-email@domain.com 
  links:
    - https://github.com/xrviv # Your primary link
